apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipfs-testbed.fullname" . }}-toxiproxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ipfs-testbed.name" . }}
    helm.sh/chart: {{ include "ipfs-testbed.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  proxy-config.json: | {{ toJson .Values.toxiproxy.config | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipfs-testbed.fullname" . }}-ipfs-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ipfs-testbed.name" . }}
    helm.sh/chart: {{ include "ipfs-testbed.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ipfs-config.json: | {{ toJson .Values.ipfs.config  | nindent 4 }}
