apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-testbed.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ipfs-testbed.name" . }}
    helm.sh/chart: {{ include "ipfs-testbed.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ipfs-testbed.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: swarm
      protocol: TCP
      port: {{ .Values.service.swarm.port }}
      targetPort: toxiproxy-proxy
    - name: toxiproxy-api
      protocol: TCP
      port: {{ .Values.service.toxiproxyAPI.port }}
      targetPort: 8474
    - name: toxiproxy-api
      protocol: TCP
      port: {{ .Values.service.ipfsAPI.port }}
      targetPort: ipfs-api
